/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-11-19 14:10:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.net.URLDecoder;
import java.util.Locale;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("  Created by IntelliJ IDEA.\r\n");
      out.write("  User: hblvs\r\n");
      out.write("  Date: 2017/11/10\r\n");
      out.write("  Time: 22:01\r\n");
      out.write("  To change this template use File | Settings | File Templates.\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DDOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.myTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/top.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/container.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/libraryContainer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/commentContainer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/animation.css\">\r\n");
      out.write("    <script type=\"text/javascript\"  src=\"/Blog_jsp/js/pretreatment.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Blog_jsp/js/treatment.js\" ></script>\r\n");
      out.write("    <!--src=\"http://maps.google.com/maps/api/js?sensor=false\"-->\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body onmousedown=\"rightKey()\" onload=\"load()\">\r\n");
      out.write("\t<header id=\"top\">\r\n");
      out.write("\t        <h1 align=\"center\" id=\"biaoti\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.myTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\t    <h5 id=\"vistor\">\r\n");
      out.write("\t        <input type=\"button\" id=\"btn_checkCache\" value=\"检查缓存\" onclick=\"checkCache()\">\r\n");
      out.write("\t        <input type=\"button\" id=\"btn_undataCache\" value=\"更新缓存\" onclick=\"updateMyCache()\"><br>\r\n");
      out.write("\t        总访问数：<input type=\"text\"  id=\"vistorNumber\" width=\"auto\" onclick=\"inialVistorNumber()\" \r\n");
      out.write("\t        value=\"");
      out.print( application.getAttribute("count") );
      out.write("\" ><br>\r\n");
      out.write("\t        当前会话内访问数：<input type=\"text\"  id=\"vistorNumberTime\" width=\"auto\" onclick=\"inialVistorNumberTime()\" >\r\n");
      out.write("\t    </h5>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t    <nav id=\"myNav\" draggable=\"true\">\r\n");
      out.write("\t        <p>\t<MARK><b>技术分类</b></MARK></p>\r\n");
      out.write("\t        <ul>\r\n");
      out.write("\t            <li><a href=\"#theam_桌面端\">桌面端</a></li>\r\n");
      out.write("\t            <li><a href=\"#theam_移动端\">移动端</a></li>\r\n");
      out.write("\t            <li><a href=\"#theam_网页端\">网页端</a></li>\r\n");
      out.write("\t            <li><a href=\"#theam_服务器端\">服务器端</a></li>\r\n");
      out.write("\t            <li><a href=\"/Blog_jsp/html/Login.html\">用户登陆界面</a></li>\r\n");
      out.write("\t            <li><a href=\"/Blog_jsp/TestServlet\">访问TestServlet</a></li>\r\n");
      out.write("\t            <li><a href=\"/Blog_jsp/TestJDBCServlet\">访问TestJDBC</a></li>\r\n");
      out.write("\t            <li><a href=\"/Blog_jsp/jsp/TestEL.jsp?name=TestEL\">访问TestEL</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t        <P id=\"myTime\">2017-11-09</P>\r\n");
      out.write("\t    </nav>\r\n");
      out.write("\t    <div id=\"myNav2\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"myArticle\">\r\n");
      out.write("\t        <section id=\"theam_桌面端\">\r\n");
      out.write("\t            <HEADER>\r\n");
      out.write("\t                <P>桌面端</P>\r\n");
      out.write("\t            </HEADER>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>C/C++</li>\r\n");
      out.write("\t                <li>Java</li>\r\n");
      out.write("\t                <li>VB</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t        <section id=\"theam_移动端\" >\r\n");
      out.write("\t            <HEADER>\r\n");
      out.write("\t                <P>移动端</P>\r\n");
      out.write("\t            </HEADER>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>Android</li>\r\n");
      out.write("\t                <li>IOS</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t        <section id=\"theam_网页端\" >\r\n");
      out.write("\t            <HEADER>\r\n");
      out.write("\t                <P>网页端</P>\r\n");
      out.write("\t            </HEADER>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>HTML/XHTML/HTML5</li>\r\n");
      out.write("\t                <li>CSS</li>\r\n");
      out.write("\t                <li>Java Script</li>\r\n");
      out.write("\t                <li>Node.js</li>\r\n");
      out.write("\t                <li>PHP</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t        <section id=\"theam_服务器端\" >\r\n");
      out.write("\t            <HEADER>\r\n");
      out.write("\t                <P>服务器端</P>\r\n");
      out.write("\t            </HEADER>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>UNIX/Linux</li>\r\n");
      out.write("\t                <li>SQL Sever</li>\r\n");
      out.write("\t                <li>MySQL</li>\r\n");
      out.write("\t                <li>MongoDB</li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </section>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"myAside\">\r\n");
      out.write("\t    ");

	        Cookie[] cookies=request.getCookies();
	        String cookieUser="";
	        String cookieData="";
	        if (cookies != null){
	            for(int i=0;i<cookies.length;i++){
	                if(cookies[i].getName().equals("myCookie")){	                 
	                    cookieUser= URLDecoder.decode(cookies[i].getValue().split("#")[0],"UTF-8");
	                    cookieData=URLDecoder.decode(cookies[i].getValue().split("#")[1].toString(),"UTF-8");
	                };
	            };
	        }
	        boolean isQuitSignIn=false;
	        if("true".equals(request.getParameter("isQuitSignIn"))){
	        	isQuitSignIn=true;
	        }
	        String fromPage="";
	        boolean fromPageSignInCheckServlet=false;
	        boolean isSignInFinish=false;
	        boolean signInFlag=false;
	        boolean hasSignInName=false;
	        if(null!=request.getParameter("fromPage")){
	        	fromPageSignInCheckServlet=("SignInCheckServlet".equals(request.getParameter("fromPage").toString()))?true:false;
	        }
	        if(null!=session.getAttribute("isSignInFinish")){
	        	isSignInFinish=(Boolean)session.getAttribute("isSignInFinish");
	        }
	        if(null!=session.getAttribute("signInFlag")){
	        	signInFlag=(Boolean)session.getAttribute("signInFlag");
	        }
	        if(null!=session.getAttribute("hasSignInName")){
	        	hasSignInName=(Boolean)session.getAttribute("hasSignInName");
	        }
	        if(fromPageSignInCheckServlet && isSignInFinish && !signInFlag && hasSignInName){
       	
      out.write("\r\n");
      out.write("\t        \t<script type=\"text/javascript\">alert(\"密码错误，请重新登陆\")</script>\r\n");
      out.write("\t   \t");

	        }else if(fromPageSignInCheckServlet && isSignInFinish && !signInFlag && !hasSignInName){
       	
      out.write("\r\n");
      out.write("\t        \t<script type=\"text/javascript\">alert(\"用户不存在，请注册新用户 \")</script>\r\n");
      out.write("\t   \t");

	        }else if(fromPageSignInCheckServlet && !isSignInFinish){
       	
      out.write("\r\n");
      out.write("\t        \t<script type=\"text/javascript\">alert(\"登陆信息填写不完整，请填写完整! \")</script>\r\n");
      out.write("\t   \t");

	        }
	        if (fromPageSignInCheckServlet && signInFlag){
	  	
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"form1\" name=\"form1\" method=\"post\" action=\"");
      out.print( request.getContextPath());
      out.write("/SignInCheckServlet\" target=\"_self\">\t\r\n");
      out.write("\t\t\t       <P>欢迎<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>再次光临</P>\r\n");
      out.write("\t\t\t       <P>您的注册时间是：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.signUpTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</P>\r\n");
      out.write("\t\t\t       <input type=\"submit\" name=\"btnQuitSignIn\" class=\"btn_grey\" value=\"退出登陆\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t  \t</form> \r\n");
      out.write(" \t\t");

      		}else{
   		
      out.write("\r\n");
      out.write("   \t\t\t\t<form id=\"form1\" name=\"form1\" method=\"post\" action=\"");
      out.print( request.getContextPath());
      out.write("/SignInCheckServlet\" target=\"_self\">\t\r\n");
      out.write("\t\t           <table id=\"myTable\">\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td  colspan=\"2\"  bgcolor=\"#eeeeee\">·用户登录</td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td width=\"20%\" >用户名:</td>\r\n");
      out.write("\t\t                   <td><input type=\"text\" name=\"user\" id=\"user\" width=\"100px\" onclick=\"setUserName()\" class=\"table_input\"></td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td>密&nbsp;&nbsp;&nbsp;&nbsp;码：</td>\r\n");
      out.write("\t\t                   <td ><input type=\"password\" name=\"pwd\" id=\"pwd\" onclick=\"setPassword()\" class=\"table_input\" ></td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td >性别：</td>\r\n");
      out.write("\t\t                   <td >\r\n");
      out.write("\t\t                       <select name=\"sex\" id=\"sex\" size=\"digit\" >\r\n");
      out.write("\t\t                           <option>男生&nbsp;&nbsp;&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t                           <option>女生&nbsp;&nbsp;&nbsp;&nbsp;</option>\r\n");
      out.write("\t\t                       </select>\r\n");
      out.write("\t\t                   </td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td colspan=\"2\">\r\n");
      out.write("\t\t                       <input type=\"checkbox\" name=\"checkbox1\" id=\"checkbox1\" value=\"Apple\"> Apple&nbsp;\r\n");
      out.write("\t\t                       <input type=\"checkbox\" name=\"checkbox2\" id=\"checkbox2\" value=\"Orange\"> Orange&nbsp;\r\n");
      out.write("\t\t                       <input type=\"checkbox\" name=\"checkbox3\" id=\"checkbox3\" value=\"Pear\"> Pear&nbsp;\r\n");
      out.write("\t\t                   </td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t                   \t<input type=\"submit\" id=\"signin\" name=\"signin\" class=\"btn_grey\" value=\"登陆\" onclick=\"check()\"/>&nbsp;&nbsp;\r\n");
      out.write("\t\t                       <input type=\"button\" id=\"signup\" name=\"signup\" class=\"btn_grey\" value=\"注册\" onclick=\"jumpToSignUpPage()\">&nbsp;&nbsp;\r\n");
      out.write("\t\t                       <input type=\"reset\" name=\"Submit2\" class=\"btn_grey\" value=\"重置\">&nbsp;&nbsp;\r\n");
      out.write("\t\t                   </td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t               <tr>\r\n");
      out.write("\t\t                   <td  colspan=\"2\">\r\n");
      out.write("\t\t                   </td>\r\n");
      out.write("\t\t               </tr>\r\n");
      out.write("\t\t           </table>\r\n");
      out.write("   \t\t\t\t</form>\t    \r\n");
      out.write("      \t");

          	}
	  	
      out.write("\r\n");
      out.write("\t\t        <div id=\"myImage\"><img src=\"/Blog_jsp/img/zjl.jpg\"></div>\r\n");
      out.write("\t\t        <div id=\"myAudio\">\r\n");
      out.write("\t\t            <audio id=\"music\"  controls=\"controls\" onmousemove=\"this.play()\" onmouseout=\"this.pause()\" preload=\"auto\">\r\n");
      out.write("\t\t                <source src=\"/Blog_jsp/music/anjing.wav\" type=\"audio/wav\">\r\n");
      out.write("\t\t            </audio>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t        <p align=\"center\"><button id=\"toggle\" onclick=\"toggleSound()\" >播放</button></p>\r\n");
      out.write("\t\t        <p align=\"center\"><button id=\"communication\" onclick=\"workerMethod()\" >线程间通讯</button></p>\r\n");
      out.write("\t\t        <canvas id=\"myCanvas\"></canvas>\r\n");
      out.write("\t\t        <script type=\"text/javascript\">\r\n");
      out.write("\t\t            var c=document.getElementById(\"myCanvas\");\r\n");
      out.write("\t\t            var context=c.getContext(\"2d\");\r\n");
      out.write("\t\t            if (c.getContext==false) {\r\n");
      out.write("\t\t                alert(\"你的浏览器不支持canvas元素，请更新或者更换您的浏览器。\")\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t            //context.moveTo(0,0);\r\n");
      out.write("\t\t            //context.lineTo(200,100);\r\n");
      out.write("\t\t            //context.stroke();\r\n");
      out.write("\t\t            //context.fillStyle=\"#FF00FF\";\r\n");
      out.write("\t\t            //context.fillRect(0,0,200,100);\r\n");
      out.write("\t\t            for(var i=0;i<20;i++){\r\n");
      out.write("\t\t                context.strokeStyle=\"#FF00FF\";\r\n");
      out.write("\t\t                context.beginPath();\r\n");
      out.write("\t\t                context.arc(0,100,i*5,0,Math.PI*3/2,true);\r\n");
      out.write("\t\t                context.stroke();\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        </script>\r\n");
      out.write("\t\t        <div id=\"fibonacci\">\r\n");
      out.write("\t\t            请输入Fibonacci的N值：<input type=\"text\" id=\"text_fibonacci\">\r\n");
      out.write("\t\t            <button id=\"btn_fibonacci\" onclick=\"fibonacci()\">计算</button>\r\n");
      out.write("\t\t            <input type=\"text\" id=\"result_fibonacci\">\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"library\">\r\n");
      out.write("\t\t<div id=\"bookInfor\">\r\n");
      out.write("\t\t\t<form id=\"formBookInfor\" action=\"");
      out.print( request.getContextPath());
      out.write("/AddServlet\" target=\"_self\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table id=\"tableBookInfor\">\r\n");
      out.write("\t\t\t\t<caption>添加图书信息</caption>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>图书编号：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"inputBookInforID\" name=\"inputBookInforID\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>图书名称：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"inputBookInforName\" name=\"inputBookInforName\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;者：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"inputBookInforAuthor\" name=\"inputBookInforAuthor\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>价&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;格：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"inputBookInforPrice\" name=\"inputBookInforPrice\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>数&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;量：</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"inputBookInforNumber\" name=\"inputBookInforNumber\"/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" id=\"inputBookInforSummit\" name=\"inputBookInforSummit\" value=\"提交\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"checkEmailAndPhone\">\r\n");
      out.write("\t\t\t");
      com.lvhongbin.bean.EmailCheck emailCheck = null;
      emailCheck = (com.lvhongbin.bean.EmailCheck) _jspx_page_context.getAttribute("emailCheck", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (emailCheck == null){
        emailCheck = new com.lvhongbin.bean.EmailCheck();
        _jspx_page_context.setAttribute("emailCheck", emailCheck, javax.servlet.jsp.PageContext.PAGE_SCOPE);
        out.write("\r\n");
        out.write("\t        ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("emailCheck"), "phoneAdd", "15821717328", null, null, false);
        out.write("\r\n");
        out.write("\t        ");
      }
      out.write("\r\n");
      out.write("\t        <form id=\"checkForm\"  action=\"/Blog_jsp/jsp/mailCheck.jsp\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t            <table id=\"checkTable\">\r\n");
      out.write("\t                <caption>验证系统 ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.lvhongbin.bean.EmailCheck)_jspx_page_context.findAttribute("emailCheck")).getPhoneAdd())));
      out.write("</caption>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td align=\"center\">电话号码</td>\r\n");
      out.write("\t                    <td align=\"center\"><input type=\"text\" id=\"phoneCheck\" name=\"phoneCheck\"></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td align=\"center\">邮箱地址</td>\r\n");
      out.write("\t                    <td align=\"center\"><input type=\"text\" id=\"mailCheck\"  name=\"mailCheck\"></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td colspan=\"2\" align=\"center\"><input type=\"submit\" id=\"summitCheck\"></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"libraryOther\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( request.getContextPath());
      out.write("/UploadServlet\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("\t\t\t\t选择文件<input type=\"file\" name=\"file1\" id=\"file1\">\r\n");
      out.write("\t\t\t\t<input type=\"submit\" name=\"upload\" id=\"upload\" value=\"上传\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"commentContainer\">\r\n");
      out.write("\t    <div id=\"videoArea\">\r\n");
      out.write("\t        <video id=\"video\" width=\"600px\" height=\"400px\"  onmousemove=\"this.play()\" onmouseout=\"this.pause()\" preload=\"metadata\"  controls=\"controls\"\r\n");
      out.write("\t               oncanplay=\"startVideo()\" onended=\"stopTimeline()\">\r\n");
      out.write("\t            <source src=\"/Blog_jsp/video/video.mp4\" type=\"video/mp4\">\r\n");
      out.write("\t        </video>\r\n");
      out.write("\t        <canvas id=\"timeline\" width=\"400px\" height=\"300px\"></canvas>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div id=\"commentArea\">\r\n");
      out.write("\t        <div id=\"commentAreaContainer\">\r\n");
      out.write("\t            <div id=\"commentFormDiv\">\r\n");
      out.write("\t                <form id=\"commentForm\">\r\n");
      out.write("\t                    <table id=\"commentTable\">\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                            <td id=\"commenter\"  style=\"width: 10em\">评论人</td>\r\n");
      out.write("\t                            <td id=\"comment\" >评论内容</td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                    </table>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div id=\"commentInfoFormDiv\">\r\n");
      out.write("\t                <form id=\"commenterInfoForm\" method=\"get\" action=\"\">\r\n");
      out.write("\t                    <table id=\"commenterInfoTable\">\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                            <td style=\"width: 5em\">评论人：&nbsp;&nbsp;</td>\r\n");
      out.write("\t                            <td><input id=\"commenterName\" type=\"text\"></td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                        <tr>\r\n");
      out.write("\t                            <td>评论内容：</td>\r\n");
      out.write("\t                            <td ><textarea id=\"commenterText\" rows=\"6\"></textarea></td>\r\n");
      out.write("\t                        </tr>\r\n");
      out.write("\t                    </table>\r\n");
      out.write("\t                </form>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <div id=\"commentButtonDiv\">\r\n");
      out.write("\t                <input type=\"button\" id=\"commentPublic\" value=\"发表\" onclick=\"addComment()\">\r\n");
      out.write("\t                <input type=\"button\" id=\"commentReset\" value=\"重置\" onclick=\"clearComment()\">\r\n");
      out.write("\t                <input type=\"button\" id=\"commentDeleteFirst\" value=\"删除第一条评论\" onclick=\"deleteFirstComment()\">\r\n");
      out.write("\t                <input type=\"button\" id=\"commentDeleteLast\" value=\"删除最后一条评论\" onclick=\"deleteLastComment()\">\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t        <P>Copyright@冰先生</P>\r\n");
      out.write("\t    <a href=\"http://www.sjtu.edu.cn/\" style=\"color:white;\">上海交通大学<br></a>\r\n");
      out.write("\t    ");
      com.lvhongbin.bean.ShowTime showTime = null;
      showTime = (com.lvhongbin.bean.ShowTime) _jspx_page_context.getAttribute("showTime", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (showTime == null){
        showTime = new com.lvhongbin.bean.ShowTime();
        _jspx_page_context.setAttribute("showTime", showTime, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\t    <time pubdate datetime=\"2017-10-26 10:57\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.lvhongbin.bean.ShowTime)_jspx_page_context.findAttribute("showTime")).getRealTime())));
      out.write("</time>\r\n");
      out.write("\t    </footer>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
