/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-11-19 12:32:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lvhongbin.bean.User;
import java.util.Date;
import java.net.URLEncoder;
import javafx.scene.control.Alert;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.lvhongbin.bean.User");
    _jspx_imports_classes.add("javafx.scene.control.Alert");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.util.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<title>用户注册</title>\r\n");
      out.write("\t\t<link href=\"css/signUp.css\" type=\"text/css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/Blog_jsp/css/signUp.css\">\r\n");
      out.write("\t\t<script type=\"text/javascript\"  src=\"/Blog_jsp/js/signUp.js\" charset=\"UTF-8\"></script>\r\n");
      out.write("\t\t<style type=\"text/css\">\r\n");
      out.write("\t\t\tbody{\r\n");
      out.write("\t\t\t\tmargin: 0px;font-size: 12px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.box{\r\n");
      out.write("\t\t\t\tborder: 1px solid #D1DEB2; width: 150px; height: 20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.div1{\r\n");
      out.write("\t\t\t\tbackground-image: url(images/bg.jpg);\r\n");
      out.write("\t\t\t\theight: 600px;\r\n");
      out.write("\t\t\t\twidth: 803px;\r\n");
      out.write("\t\t\t\tpadding-left:20px;\r\n");
      out.write("\t\t\t\tpadding-top:220px;\r\n");
      out.write("\t\t\t\ttext-align:left;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t");

		System.out.println("======== 跳转到signUp页面 ========");
		boolean fromPageSignUpCheckServlet=false;
		boolean isExisted=false;
        boolean signUpFlag=false;
        boolean isSignUpFinish=false;
        User user =null;
        if(null!=request.getParameter("fromPage")){
        	fromPageSignUpCheckServlet=("SignUpCheckServlet".equals(request.getParameter("fromPage").toString()))?true:false;
        }
        if(null!=session.getAttribute("isSignUpFinish")){
        	isSignUpFinish=(Boolean)session.getAttribute("isSignUpFinish");
        }
        if(null!=session.getAttribute("isExisted")){
        	isExisted=(Boolean)session.getAttribute("isExisted");
        }
        if(null!=session.getAttribute("signUpFlag")){
        	signUpFlag=(Boolean)session.getAttribute("signUpFlag");
        }
        if(null!=session.getAttribute("user")){
        	user=(User)session.getAttribute("user");
        }
        if(fromPageSignUpCheckServlet){
        	if(isSignUpFinish){
        		if(isExisted){
		
      out.write("\t \r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\t\t\t\t\t\t alert(\"用户名已存在，请重新填写用户名，或者选择直接登陆\");\r\n");
      out.write("\t\t\t\t\t</script> \r\n");
      out.write("\t\t");

 		    		System.out.println("======== 注册失败,用户账号已存在 ========");
 				}else if(signUpFlag){
        
      out.write("\r\n");
      out.write("\t\t\t\t\t <script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\t\t\t\t\t\t function alertmessage(){\r\n");
      out.write("\t\t\t\t\t\t\t var username=window.document.getElementById(\"username\");\r\n");
      out.write("\t\t\t\t\t\t\t alert(\"恭喜 \"+username+\" ,注册成功,3秒后跳转原页面\");\r\n");
      out.write("\t\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t\t setTimeout(\"alertmessage()\", 3000); \r\n");
      out.write("\t\t\t\t\t </script>\r\n");
      out.write("\t\t");

   						System.out.println("======== 注册成功，准备离开到signUp页面 ========");
   			       		response.sendRedirect("/Blog_jsp/SignInCheckServlet?fromPage=signUp");
   				}else{
        
      out.write("\r\n");
      out.write("   \t\t\t\t\t\t <script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("   \t\t\t\t\t\t \talert(\"数据库写入失败,请检查拼写\");\r\n");
      out.write("   \t\t\t\t\t\t </script>\r\n");
      out.write("        ");

        		}
        	}else{
        
      out.write("\r\n");
      out.write("\t\t\t\t\t <script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\t\t\t\t\t \talert(\"注册信息填写不完整,请重新填写\");\r\n");
      out.write("\t\t\t\t\t </script>\r\n");
      out.write("\t\t");

        	}	
        }
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<div class=\"div1\">\r\n");
      out.write("\t\t\t\t<form action=\"/Blog_jsp/SignUpCheckServlet\" method=\"post\" onsubmit=\"return reg(this);\">\r\n");
      out.write("\t\t\t\t\t<table align=\"center\" border=\"0\" width=\"500\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\" width=\"30%\" size =\"9pt\">用户名：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input  id=\"username\" name=\"username\" type=\"text\"  class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">密 码：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">确认密码：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"password\" name=\"repassword\" class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr> \r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">性 别：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"男\" checked=\"checked\">男\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"女\">女\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">密码找回问题：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"question\" class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">密码找回答案：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"answer\" class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"right\">邮 箱：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"email\" class=\"box\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\" align=\"center\" height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"注 册\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"reset\" value=\"重 置\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
